version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      target: runner
    environment:
      DATABASE_URL: mysql://root:root@localhost:3306/appdb
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 3000:3000

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
